In [1]:
from tensorflow.keras.layers import Input
inputs = Input(shape=(10,))

In [2]:
from tensorflow.keras.layers import Input,Dense
inputs = Input(shape=(10,))
hidden1 = Dense(64,activation='relu')(inputs)
hidden2 = Dense(64,activation='relu')(hidden1)
output = Dense(1,activation='sigmoid')(hidden2)

In [4]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
inputs =Input(shape=(10,))
hidden1 = Dense(64,activation='relu')(inputs)
hidden2 = Dense(64,activation='relu')(hidden1)
output = Dense(1, activation='sigmoid')(hidden2)
model = Model(inputs=inputs,outputs=output)

In [8]:
from tensorflow.keras.layers import Input, Dense, concatenate
from tensorflow.keras.models import Model

inputA = Input(shape=(64,))
inputB = Input(shape=(128,))

x = Dense(16,activation='relu')(inputA)
x = Dense(8,activation='relu')(x)
x = Model(inputs=inputA,outputs=x)

y = Dense(64,activation='relu')(inputB)
y = Dense(32,activation='relu')(y)
y = Dense(8,activation='relu')(y)
y = Model(inputs=inputB, outputs=y)

result = concatenate([x.output, y.output])
z = Dense(2, activation='relu')(result)
z = Dense(1, activation='linear')(z)

model = Model(inputs = [x.input, y.input],outputs=z)

In [11]:
from tensorflow.keras.layers import Input, Dense, LSTM
from tensorflow.keras.models import Model
inputs = Input(shape=(50,1))
lstm_layer = LSTM(10)(inputs)
x = Dense(10,activation='relu')(lstm_layer)
x = Dense(10,activation='relu')(lstm_layer)
output = Dense(1, activation='sigmoid')(x)
model = Model(inputs=inputs, outputs=output)

In [12]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

texts = ['먹고 싶은 사과', '먹고 싶은 바나나', 
       '길고 노란 바나나 바나나', '저는 과일이 좋아요']

t = Tokenizer()
t.fit_on_texts(texts)
print(t.word_index)

{'바나나': 1, '먹고': 2, '싶은': 3, '사과': 4, '길고': 5, '노란': 6, '저는': 7, '과일이': 8, '좋아요': 9}


In [15]:
print(t.texts_to_matrix(texts, mode='count'))
print(t.texts_to_matrix(texts, mode='binary'))

[[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]
[[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [18]:
print(t.texts_to_matrix(texts, mode='tfidf').round(2))

[[0.   0.   0.85 0.85 1.1  0.   0.   0.   0.   0.  ]
 [0.   0.85 0.85 0.85 0.   0.   0.   0.   0.   0.  ]
 [0.   1.43 0.   0.   0.   1.1  1.1  0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   1.1  1.1  1.1 ]]


In [19]:
print(t.texts_to_matrix(texts, mode='freq').round(2))

[[0.   0.   0.33 0.33 0.33 0.   0.   0.   0.   0.  ]
 [0.   0.33 0.33 0.33 0.   0.   0.   0.   0.   0.  ]
 [0.   0.5  0.   0.   0.   0.25 0.25 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.33 0.33 0.33]]


In [21]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
%matplotlib inline
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [23]:
newsdata =fetch_20newsgroups(subset='train')

In [24]:
print(newsdata.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [28]:
len(newsdata['data']) # 훈련용 샘플 개수 11314

11314

In [32]:
len(newsdata.target_names) # 총 주제 개수 : 20
print(newsdata.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [34]:
newsdata.target[0]

7

In [35]:
newsdata.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [36]:
newsdata.target_names[7]

'rec.autos'

In [37]:
print(newsdata.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [38]:
data = pd.DataFrame(newsdata.data, columns = ['email'])
data['target'] = pd.Series(newsdata.target)
data[:5]

email  target
0  From: lerxst@wam.umd.edu (where's my thing)\nS...       7
1  From: guykuo@carson.u.washington.edu (Guy Kuo)...       4
2  From: twillis@ec.ecn.purdue.edu (Thomas E Will...       4
3  From: jgreen@amber (Joe Green)\nSubject: Re: W...       1
4  From: jcm@head-cfa.harvard.edu (Jonathan McDow...      14

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11314 entries, 0 to 11313
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   email   11314 non-null  object
 1   target  11314 non-null  int32 
dtypes: int32(1), object(1)
memory usage: 132.7+ KB


In [42]:
data.isnull().values.any()

False

In [48]:
print(data['email'].nunique())
print(data['target'].nunique())

11314
20


In [51]:
print(data.groupby('target').size().reset_index(name='count'))

    target  count
0        0    480
1        1    584
2        2    591
3        3    590
4        4    578
5        5    593
6        6    585
7        7    594
8        8    598
9        9    597
10      10    600
11      11    595
12      12    591
13      13    594
14      14    593
15      15    599
16      16    546
17      17    564
18      18    465
19      19    377


In [53]:
newsdata_test = fetch_20newsgroups(subset='test',shuffle=True)
train_email = data['email']
train_label = data['target']
test_email = newsdata_test.data
test_label = newsdata_test.target

In [54]:
max_words = 10000
num_classes = 20

In [61]:
def prepare_data(train_data, test_data, mode):
    t = Tokenizer(num_words = max_words)
    t.fit_on_texts(train_data)
    X_train = t.texts_to_matrix(train_data, mode = mode)
    X_test = t.texts_to_matrix(test_data, mode=mode)
    return X_train, X_test, t.index_word

In [64]:
X_train, X_test, index_to_word = prepare_data(train_email, test_email, 'binary')
y_train = to_categorical(train_label, num_classes)
y_test = to_categorical(test_label, num_classes)

In [66]:
print(X_train.shape) # train sample : 11314, 10000
print(y_train.shape) # train label : 11314, 20
print(X_test.shape) # test data : 7532, 10000
print(y_test.shape) # 7532, 20

(11314, 10000)
(11314, 20)
(7532, 10000)
(7532, 20)


In [70]:
print(index_to_word[1])
type(index_to_word)


the


dict

In [72]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [75]:
def fit_and_evaluate(X_trian, y_train, X_test, y_test):
    model = Sequential()
    model.add(Dense(256, input_shape=(max_words,),activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_classes,activation='softmax'))
    
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.fit(X_train, y_train, batch_size=128, epochs=5, verbose=1, validation_split=0.1)
    score = model.evaluate(X_test, y_test, batch_size=128, verbose=0)
    return score[1]

In [76]:
modes = ['binary', 'count','tfidf','freq']
for mode in modes:
    X_train, X_test, _ = prepare_data(train_email, test_email, mode)
    score = fit_and_evaluate(X_train, y_train, X_test, y_test)
    print(mode, 'accuracy : ', score)

Epoch 1/5
80/80 [==============================] - 1s 12ms/step - loss: 2.2498 - accuracy: 0.3505 - val_loss: 0.9482 - val_accuracy: 0.8207
Epoch 2/5
80/80 [==============================] - 1s 10ms/step - loss: 0.8690 - accuracy: 0.7576 - val_loss: 0.4573 - val_accuracy: 0.8940
Epoch 3/5
80/80 [==============================] - 1s 10ms/step - loss: 0.4334 - accuracy: 0.8832 - val_loss: 0.3474 - val_accuracy: 0.9019
Epoch 4/5
80/80 [==============================] - 1s 10ms/step - loss: 0.2565 - accuracy: 0.9346 - val_loss: 0.3159 - val_accuracy: 0.9064
Epoch 5/5
80/80 [==============================] - 1s 10ms/step - loss: 0.1728 - accuracy: 0.9551 - val_loss: 0.3102 - val_accuracy: 0.9108
binary accuracy :  0.8267392516136169
Epoch 1/5
80/80 [==============================] - 1s 11ms/step - loss: 2.7423 - accuracy: 0.2570 - val_loss: 1.5707 - val_accuracy: 0.7049
Epoch 2/5
80/80 [==============================] - 1s 10ms/step - loss: 1.4045 - accuracy: 0.6370 - val_loss: 0.7386 - val