In [1]:
X,y = zip(['a',1],['b',2],['c',3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [2]:
sequences = [['a',1],['b',2],['c',3]]
X,y = zip(*sequences)
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [5]:
import numpy as np
ar = np.arange(0,16).reshape((4,4))
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
X = ar[:,:3]
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [7]:
y = ar[:,3]
print(y)

[ 3  7 11 15]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1234)

In [13]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[0 1 2]]
[ 7 11 15]
[3]


In [27]:
import numpy as np
X, y = np.arange(10).reshape((5,2)), range(5)

In [31]:
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [35]:
X_trian, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 1234)

In [36]:
print(X_train)
print(X_test)

[[2 3]
 [4 5]
 [6 7]]
[[8 9]
 [0 1]]


In [37]:
print(y_train)
print(y_test)

[1, 2, 3]
[4, 0]


In [38]:
import numpy as np
X,y = np.arange(0,24).reshape((12,2)),range(12)

In [42]:
n_of_train = int(len(X) * 0.8)
n_of_test = int(len(X) - n_of_train)
print(n_of_train)
print(n_of_test)

9
3


In [43]:
X_test = X[n_of_train:]
y_test = y[n_of_train:]
X_train = X[:n_of_train]
y_train = y[:n_of_train]

In [44]:
X_test

array([[18, 19],
       [20, 21],
       [22, 23]])

In [46]:
list(y_test)

[9, 10, 11]